# Numpy built-in functions:

## 1. Array Creation Functions

In [1]:
import numpy as np

In [2]:
# create an array from a list
a = np.array([1,2,3])
print('Array a:', a)

Array a: [1 2 3]


In [4]:
# create an array with evenly spaced values
b = np.arange(0,10,3) # values from 0 to 10 with 2 steps
print("Array b:", b)

Array b: [0 3 6 9]


In [9]:
# create an array filled with zeroes
d = np.zeros((2,3)) # 2x3 matrix of zeroes
print('Array d:\n', d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# create an arrya filled with zeroes of integer type
d = np.zeros((2,3), dtype = int) # 2x3 matrix with zeros
print('Array d:\n', d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [11]:
# create an array filled with ones
e = np.ones((3,2)) # 3x2 matrix of ones
print('Array e:\n', e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
# create an array filled with ones
e = np.ones((2,3), dtype = int)
print('Array e:\n', e)

Array e:
 [[1 1 1]
 [1 1 1]]


In [13]:
# create an identity matrix where all the diagonals are one
f = np.eye(4) # 4x4 identity matrix
print('Identity matrix f:\n', f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
f = np.eye(4, dtype = int)
print('Identity matrix f:\n', f)

Identity matrix f:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## 2. Array Manipulation Functions

In [16]:
# Reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (1,3)) # reshape to 1x3 matrix
print('Reshaped Array:', reshaped)

Reshaped Array: [[1 2 3]]


In [18]:
# Reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (3,1)) # reshape to 3x1 matrix
print('Reshaped Array:\n', reshaped)

Reshaped Array:
 [[1]
 [2]
 [3]]


In [23]:
# Flatten an array
f1 = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
flattened = np.ravel(f1) # flatten to 1d array
print('Flattened array:\n', flattened)

Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10]


In [25]:
# Transpose an array
e1 = np.array([[1,2], [3,4]])
transposed = np.transpose(e1) # transpose the array e1
print('Transposed array:\n', transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [30]:
# stack arrays vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2]) # stack a2 and b2 vertically
print('Stacked arrays:\n', stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [31]:
# stack arrays horizontally
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2]) # stack a2 and b2 horizontally
print('Stacked arrays:\n', stacked)

Stacked arrays:
 [1 2 3 4]


## 3. Mathematical Functions

In [32]:
# Add two arrays
g = np.array([1,2,3,4,5])
added = np.add(g,2) # add 2 to each element
print('Added 2 to g:', added)

Added 2 to g: [3 4 5 6 7]


In [33]:
# square each element
squared = np.power(g,2) # square each element
print('Squared g:', squared)

Squared g: [ 1  4  9 16 25]


In [34]:
# square root of each element
sqrt_val = np.sqrt(g) # square root of each element
print('Square root of g:', sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.         2.23606798]


In [35]:
print(a)
print(g)

[1 2 3]
[1 2 3 4 5]


In [36]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,g) # dot product of a and g
print('Dot product of a and g:', dot_product)

ValueError: shapes (3,) and (5,) not aligned: 3 (dim 0) != 5 (dim 0)

In [37]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [39]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a)
print('Dot product of a1 and a:', dot_product)

Dot product of a1 and a: 14


## 4. Statistical Functions

In [40]:
# finding mean
s = np.array([1,2,3,4])
mean = np.mean(s)
print('Mean of s:', mean)

Mean of s: 2.5


In [41]:
# variance of an array
var = np.var(s)
print('Variance of s:', var)

Variance of s: 1.25


In [42]:
# standard deviation of an array
std_dev = np.std(s)
print('Standard deviation of s:', std_dev)

Standard deviation of s: 1.118033988749895


In [43]:
s

array([1, 2, 3, 4])

In [44]:
# minimum element of an array
minimum = np.min(s)
print('Minimum of s:', minimum)

Minimum of s: 1


In [45]:
# Maximum element of an array
maximum = np.max(s)
print('Max of s:', maximum)

Max of s: 4


## 5. Linear Algebra Functions

In [46]:
# create a matrix
matrix = np.array([[1,2], [3,4]])
matrix

array([[1, 2],
       [3, 4]])

## 6. Random Sampling Functions

In [48]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3) # array of 3 random values between 0 and 1
print('Random values:', random_vals)

Random values: [0.7658875  0.66847517 0.11959475]


In [52]:
# set seed for reproducibility
np.random.seed(0)
# because of the seed(0) random numbers will not be generated
# Generate random values between 0 and 1
random_vals = np.random.rand(3)
print('Random values:', random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [57]:
# Generate random integers
rand_ints = np.random.randint(0,10, size = 4)
print('Random integers:', rand_ints)

Random integers: [6 7 7 8]


In [59]:
# set seed for reproducibility
np.random.seed(0)
# Generate random integers
rand_ints = np.random.randint(0,10, size = 5)
print('Random integers:', rand_ints)

Random integers: [5 0 3 3 7]


## 7. Boolean and Logical Functions

In [62]:
# check if all the elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)
print(' Are All elements True:', all_true)

 Are All elements True: False


In [63]:
logical_test = np.array([False, False, False])
all_true = np.all(logical_test) # checks if all are True
print('All elements True:', all_true)

All elements True: False


In [64]:
logical_test = np.array([True, True, True])
all_true = np.all(logical_test)
print('All elements True:', all_true)

All elements True: True


In [65]:
# check if any element is True
logical_test = np.array([False, False, True, False])
any_true = np.any(logical_test)
print('Any element True:', any_true)

Any element True: True


## 8. Set Operations

In [68]:
# intersection of two arrays
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a, set_b)
print('Intersection of a and b:', intersection)

Intersection of a and b: [3 4]


In [69]:
# union of two arrays
union = np.union1d(set_a, set_b)
print('Union of a and b:', union)

Union of a and b: [1 2 3 4 5 6]


## 9. Array Attribute Functions

In [70]:
# Array attributes
a = np.array([1,2,3])
shape = a.shape # gives the shape of the array
size = a.size # gives the number of elements present in an array
dimensions = a.ndim # number of dimensions
dtype = a.dtype # data type of the array

print('shape of a:', shape)
print('size of a:', size)
print('Number of dimensions of a:', dimensions)
print('Data type of a:', dtype)

shape of a: (3,)
size of a: 3
Number of dimensions of a: 1
Data type of a: int64


## 10. Other Functions

In [71]:
# create a copy of an array
a = np.array([1,2,3])
copied_array = np.copy(a) # creates a copy of array a
print('Copied array:', copied_array)

Copied array: [1 2 3]


In [72]:
# size in bytes of an array
array_size_in_bytes = a.nbytes # size in bytes
print('Size of a in bytes:', array_size_in_bytes)

Size of a in bytes: 24


In [73]:
# check if two arrays share memory
shared = np.shares_memory(a, copied_array)
print('Do a and copied_array share memory?', shared)

Do a and copied_array share memory? False
