# Numpy

In [26]:
import numpy as np

In [27]:
np.__version__

'2.3.5'

In [28]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [29]:
# creating a list

my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [30]:
type(my_list)

list

In [31]:
# converting the list to array

arr = np.array(my_list)

In [32]:
arr

array([0, 1, 2, 3, 4, 5])

In [33]:
type(arr)

numpy.ndarray

In [34]:
type(my_list)

list

In [35]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [36]:
# arange function == range function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [38]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [40]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
np.arange(20,10) # 1st arg should be less than the 2nd argument

array([], dtype=int64)

In [42]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [43]:
np.arange(-16, 10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [44]:
np.arange(30,20)

array([], dtype=int64)

In [45]:
np.arange(-30,20)

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [46]:
np.arange(10,10)

array([], dtype=int64)

In [47]:
np.arange()

TypeError: arange() requires stop to be specified.

In [48]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [49]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [50]:
np.arange(10,30,5,8) # up to 3 args are allowed

TypeError: Cannot interpret '8' as a data type

In [51]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
# zeros function
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
np.zeros(5, dtype = int) # this is called hyperparameter tuning

array([0, 0, 0, 0, 0])

In [55]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [56]:
zero = np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [57]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [59]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [61]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [62]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [64]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [65]:
n

(6, 7)

In [66]:
n1

(6, 8)

In [67]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [68]:
# ones functon
np.ones(3)

array([1., 1., 1.])

In [69]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [71]:
np.ones(4)

array([1., 1., 1., 1.])

In [72]:
n

(6, 7)

In [73]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [74]:
np.ones((5,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [75]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [76]:
np.threes((2,3))

AttributeError: module 'numpy' has no attribute 'threes'

In [77]:
# there are only two funcitons that is, zeros and ones

In [78]:
# rand functon
rand(2,3)

NameError: name 'rand' is not defined

In [79]:
random.rand(2,3)

NameError: name 'random' is not defined

In [80]:
np.random.rand(5)

array([0.74983357, 0.38747326, 0.16330309, 0.21672376, 0.43628669])

In [81]:
np.random.rand(2,3)

array([[0.91524265, 0.35989444, 0.78916484],
       [0.98329896, 0.69161735, 0.94210379]])

In [82]:
np.random.rand(4)

array([0.76827207, 0.76930364, 0.7782015 , 0.10859836])

In [83]:
np.random.rand(3,5)

array([[0.25241807, 0.9033533 , 0.27365855, 0.26815704, 0.27282425],
       [0.89939882, 0.28723699, 0.22245688, 0.34147802, 0.04972012],
       [0.42989855, 0.61959916, 0.79031935, 0.9633434 , 0.10682713]])

In [84]:
np.random.randint(4,6) # prints random values between 4 and 6

4

In [85]:
np.random.randint(2,20,4)

array([13,  6, 11,  3], dtype=int32)

In [86]:
np.random.randint(0,1)

0

In [87]:
np.random.randint(10,20,5)

array([11, 19, 13, 10, 11], dtype=int32)

In [88]:
np.random.randint(2,9,4)

array([5, 6, 7, 5], dtype=int32)

In [90]:
np.random.randint(3) # random values will be generated between between 3

0

In [92]:
np.random.randint(30,20,10) # the 1st arg must be greater than the 2nd

ValueError: low >= high

In [94]:
np.random.randint(-30,20,10) # this generates random numbers between -30 and 20, and 10
                             # is the number of values it prints

array([-26, -29,   0, -18,  -1, -20, -26,   4, -16,  -1], dtype=int32)

In [95]:
np.random.randint(20,30,10)

array([27, 27, 21, 28, 22, 21, 24, 29, 28, 29], dtype=int32)

In [96]:
np.random.randint(10,21,3)

array([14, 14, 18], dtype=int32)

In [97]:
np.random.randint(1,12,10)

array([ 3,  7,  8,  5,  6, 11,  8, 10,  8,  9], dtype=int32)

In [99]:
np.random.randint(10,40,(10,10))
# here, the matrix of 10 x 10 is created with values ranging from 10 to 40 randomly
# the 10 and 40 is the range from which values will be printed randomly
# (10,10) is the matrix to be created with 10 rows and 10 columns

array([[30, 23, 16, 24, 11, 34, 25, 26, 23, 31],
       [22, 17, 25, 16, 11, 28, 11, 15, 21, 22],
       [32, 37, 18, 14, 24, 33, 26, 17, 19, 33],
       [30, 29, 20, 16, 18, 23, 10, 16, 28, 15],
       [16, 24, 15, 30, 26, 35, 14, 22, 32, 37],
       [20, 39, 37, 35, 30, 24, 14, 32, 34, 32],
       [10, 14, 37, 12, 24, 37, 22, 11, 30, 28],
       [36, 14, 35, 25, 21, 20, 15, 24, 13, 17],
       [27, 26, 10, 16, 36, 37, 25, 28, 18, 21],
       [21, 37, 27, 15, 36, 33, 36, 34, 33, 29]], dtype=int32)

In [102]:
np.random.randint(1,100,(12,12))

array([[ 7, 56, 43, 29, 34, 23, 63, 27, 64, 14, 74, 58],
       [ 1, 34, 82, 58,  7, 94, 86, 71, 83, 54, 90, 60],
       [13,  3,  6, 84, 51, 12, 38,  2, 32, 56, 26, 89],
       [60, 71, 77, 19, 65, 78, 32, 54, 47, 14, 30, 44],
       [81, 64, 15, 96, 89, 30, 29, 53,  9, 99, 54, 63],
       [34, 72,  3, 95, 54, 32, 71, 13, 50, 92, 29, 91],
       [60, 34, 28, 63, 93, 21, 88, 26, 55, 47, 85, 57],
       [56, 14,  9,  8, 24, 53, 87, 16, 52, 70, 57,  7],
       [ 7, 84, 65, 23,  7, 93, 27, 37, 39, 46, 87, 59],
       [94, 61, 52, 25, 77, 58, 78, 59, 86, 63, 95, 39],
       [50, 35, 88,  1, 55, 41, 48, 14, 75, 83, 64, 78],
       [11, 75, 46, 65,  1, 67, 29, 91, 65, 47, 61, 25]], dtype=int32)

In [104]:
# small program to generate otp
import numpy as np

def generate_otp(length=4):
    # Generate OTP of given length using np.random.randint
    otp = ''.join([str(np.random.randint(0, 10)) for _ in range(length)])
    return otp

# Example usage
print("Your OTP is:", generate_otp())

Your OTP is: 7095


In [105]:
arr1 = np.random.randint(10,40,(10,10))

In [106]:
arr1

array([[34, 20, 36, 38, 37, 18, 22, 13, 25, 22],
       [25, 34, 20, 27, 22, 23, 22, 20, 21, 19],
       [34, 16, 14, 19, 11, 24, 34, 38, 19, 27],
       [18, 19, 22, 21, 23, 38, 10, 15, 10, 31],
       [12, 20, 24, 23, 13, 15, 30, 34, 13, 24],
       [29, 35, 17, 28, 12, 28, 33, 30, 21, 39],
       [12, 15, 21, 23, 33, 28, 35, 11, 39, 28],
       [18, 21, 37, 11, 29, 38, 31, 32, 13, 23],
       [16, 38, 14, 14, 33, 25, 13, 34, 12, 19],
       [10, 17, 37, 32, 27, 23, 25, 16, 10, 35]], dtype=int32)

In [107]:
print(arr1)

[[34 20 36 38 37 18 22 13 25 22]
 [25 34 20 27 22 23 22 20 21 19]
 [34 16 14 19 11 24 34 38 19 27]
 [18 19 22 21 23 38 10 15 10 31]
 [12 20 24 23 13 15 30 34 13 24]
 [29 35 17 28 12 28 33 30 21 39]
 [12 15 21 23 33 28 35 11 39 28]
 [18 21 37 11 29 38 31 32 13 23]
 [16 38 14 14 33 25 13 34 12 19]
 [10 17 37 32 27 23 25 16 10 35]]


In [110]:
type(arr1)

numpy.ndarray

In [109]:
# indexing in matrix
arr1[5] # returns the 5th row in the matrix

array([29, 35, 17, 28, 12, 28, 33, 30, 21, 39], dtype=int32)

In [184]:
arr2 = np.random.randint(2,9,(5,7))

In [185]:
print(arr2)

[[7 5 7 6 2 2 5]
 [6 6 6 6 2 8 6]
 [2 5 3 3 5 5 6]
 [4 6 6 4 5 7 7]
 [3 8 6 5 3 8 4]]


In [186]:
# reverse indexing in matrix
arr2[-3]

array([2, 5, 3, 3, 5, 5, 6], dtype=int32)

In [187]:
# slicing in Matrix
print(arr2)

[[7 5 7 6 2 2 5]
 [6 6 6 6 2 8 6]
 [2 5 3 3 5 5 6]
 [4 6 6 4 5 7 7]
 [3 8 6 5 3 8 4]]


In [188]:
arr2[:]

array([[7, 5, 7, 6, 2, 2, 5],
       [6, 6, 6, 6, 2, 8, 6],
       [2, 5, 3, 3, 5, 5, 6],
       [4, 6, 6, 4, 5, 7, 7],
       [3, 8, 6, 5, 3, 8, 4]], dtype=int32)

In [189]:
arr2[1:3]

array([[6, 6, 6, 6, 2, 8, 6],
       [2, 5, 3, 3, 5, 5, 6]], dtype=int32)

In [190]:
arr2[0:4]

array([[7, 5, 7, 6, 2, 2, 5],
       [6, 6, 6, 6, 2, 8, 6],
       [2, 5, 3, 3, 5, 5, 6],
       [4, 6, 6, 4, 5, 7, 7]], dtype=int32)

In [191]:
arr2[1,2] # returns the value at 1st row and 2nd column

np.int32(6)

In [192]:
print(arr2)

[[7 5 7 6 2 2 5]
 [6 6 6 6 2 8 6]
 [2 5 3 3 5 5 6]
 [4 6 6 4 5 7 7]
 [3 8 6 5 3 8 4]]


In [193]:
print(arr2[1,2]) # returns the value at 1st row and 2nd column

6


In [194]:
arr2[::-1] # prints the reverse of the matrix

array([[3, 8, 6, 5, 3, 8, 4],
       [4, 6, 6, 4, 5, 7, 7],
       [2, 5, 3, 3, 5, 5, 6],
       [6, 6, 6, 6, 2, 8, 6],
       [7, 5, 7, 6, 2, 2, 5]], dtype=int32)

In [195]:
print(arr2)

[[7 5 7 6 2 2 5]
 [6 6 6 6 2 8 6]
 [2 5 3 3 5 5 6]
 [4 6 6 4 5 7 7]
 [3 8 6 5 3 8 4]]


In [196]:
print(arr2[-4,-5])

6


In [197]:
print(arr2[-3,-3])

5


In [198]:
print(arr2[-5,-3])

2


In [199]:
print(arr2[-4,2])

6


In [200]:
print(arr2[-4,-2])

8


In [201]:
print(arr2[-4:2])

[[6 6 6 6 2 8 6]]


In [202]:
print(arr2[-4:-2])

[[6 6 6 6 2 8 6]
 [2 5 3 3 5 5 6]]


In [203]:
arr2[::3]

array([[7, 5, 7, 6, 2, 2, 5],
       [4, 6, 6, 4, 5, 7, 7]], dtype=int32)

In [204]:
arr2

array([[7, 5, 7, 6, 2, 2, 5],
       [6, 6, 6, 6, 2, 8, 6],
       [2, 5, 3, 3, 5, 5, 6],
       [4, 6, 6, 4, 5, 7, 7],
       [3, 8, 6, 5, 3, 8, 4]], dtype=int32)

In [205]:
arr2[3,4]

np.int32(5)

In [206]:
print(arr2[-4,-5])

6


In [207]:
print(arr2)

[[7 5 7 6 2 2 5]
 [6 6 6 6 2 8 6]
 [2 5 3 3 5 5 6]
 [4 6 6 4 5 7 7]
 [3 8 6 5 3 8 4]]


In [208]:
arr2[0,1]

np.int32(5)

In [209]:
print(arr2[0,1])

5


In [210]:
arr2[0,1] = 10

In [211]:
arr2

array([[ 7, 10,  7,  6,  2,  2,  5],
       [ 6,  6,  6,  6,  2,  8,  6],
       [ 2,  5,  3,  3,  5,  5,  6],
       [ 4,  6,  6,  4,  5,  7,  7],
       [ 3,  8,  6,  5,  3,  8,  4]], dtype=int32)

In [212]:
print(arr2[0,1])

10


In [213]:
arr2[:, 0] # this prints all the values of matrix of column 0

array([7, 6, 2, 4, 3], dtype=int32)

In [214]:
arr2[:, 3]

array([6, 6, 3, 4, 5], dtype=int32)

In [215]:
arr2[:, -3]

array([2, 2, 5, 5, 3], dtype=int32)

In [216]:
print(arr2)

[[ 7 10  7  6  2  2  5]
 [ 6  6  6  6  2  8  6]
 [ 2  5  3  3  5  5  6]
 [ 4  6  6  4  5  7  7]
 [ 3  8  6  5  3  8  4]]


In [217]:
arr2[2:5, 2:5] # prints matrix with values ranging from rows 2 to 5 and columns 2 to 5 

array([[3, 3, 5],
       [6, 4, 5],
       [6, 5, 3]], dtype=int32)

In [218]:
arr2[1:4, 2:4]

array([[6, 6],
       [3, 3],
       [6, 4]], dtype=int32)

In [219]:
# Masking or Filter in numpy

In [220]:
arr2

array([[ 7, 10,  7,  6,  2,  2,  5],
       [ 6,  6,  6,  6,  2,  8,  6],
       [ 2,  5,  3,  3,  5,  5,  6],
       [ 4,  6,  6,  4,  5,  7,  7],
       [ 3,  8,  6,  5,  3,  8,  4]], dtype=int32)

In [221]:
arr2 > 50 # compares each of the value in matrix to 50

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [222]:
arr2 > 5 # compares the values of array with 5 and returns true or false

array([[ True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True, False,  True,  True],
       [False, False, False, False, False, False,  True],
       [False,  True,  True, False, False,  True,  True],
       [False,  True,  True, False, False,  True, False]])

In [223]:
arr2[arr2 > 5] # prints all the values of arr2 with values greater than 5

array([ 7, 10,  7,  6,  6,  6,  6,  6,  8,  6,  6,  6,  6,  7,  7,  8,  6,
        8], dtype=int32)

In [224]:
arr2[arr2>=5]

array([ 7, 10,  7,  6,  5,  6,  6,  6,  6,  8,  6,  5,  5,  5,  6,  6,  6,
        5,  7,  7,  8,  6,  5,  8], dtype=int32)

In [225]:
arr2

array([[ 7, 10,  7,  6,  2,  2,  5],
       [ 6,  6,  6,  6,  2,  8,  6],
       [ 2,  5,  3,  3,  5,  5,  6],
       [ 4,  6,  6,  4,  5,  7,  7],
       [ 3,  8,  6,  5,  3,  8,  4]], dtype=int32)

In [226]:
arr2 == 5

array([[False, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False],
       [False,  True, False, False,  True,  True, False],
       [False, False, False, False,  True, False, False],
       [False, False, False,  True, False, False, False]])

In [227]:
arr2[arr2 == 5]

array([5, 5, 5, 5, 5, 5], dtype=int32)

In [228]:
arr2[arr2 != 5]

array([ 7, 10,  7,  6,  2,  2,  6,  6,  6,  6,  2,  8,  6,  2,  3,  3,  6,
        4,  6,  6,  4,  7,  7,  3,  8,  6,  3,  8,  4], dtype=int32)

In [229]:
# reshape function

In [230]:
arr

array([0, 1, 2, 3, 4, 5])

In [231]:
arr.reshape(2,3) # with reshape, the arr is created into 2 x 3 matrix

array([[0, 1, 2],
       [3, 4, 5]])

In [232]:
arr.reshape(4,3) # as the arrary arr has only 6 values, it can't be reshaped into 4x3

ValueError: cannot reshape array of size 6 into shape (4,3)

In [233]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [234]:
# THE arr MATRIX CAN ONLY BE SHAPED INTO MATRIX WITH HOLDS 6 VALUES IN IT

In [235]:
# creating a matrix with the reshape function and existing array or matrix

In [236]:
arr2

array([[ 7, 10,  7,  6,  2,  2,  5],
       [ 6,  6,  6,  6,  2,  8,  6],
       [ 2,  5,  3,  3,  5,  5,  6],
       [ 4,  6,  6,  4,  5,  7,  7],
       [ 3,  8,  6,  5,  3,  8,  4]], dtype=int32)

In [247]:
arr3 = arr2[arr2<4]

In [248]:
arr3

array([2, 2, 2, 2, 3, 3, 3, 3], dtype=int32)

In [250]:
arr3.reshape(2,4)

array([[2, 2, 2, 2],
       [3, 3, 3, 3]], dtype=int32)

In [251]:
arr

array([0, 1, 2, 3, 4, 5])

In [252]:
arr.max()

np.int64(5)

In [253]:
arr.min()

np.int64(0)

In [254]:
arr2

array([[ 7, 10,  7,  6,  2,  2,  5],
       [ 6,  6,  6,  6,  2,  8,  6],
       [ 2,  5,  3,  3,  5,  5,  6],
       [ 4,  6,  6,  4,  5,  7,  7],
       [ 3,  8,  6,  5,  3,  8,  4]], dtype=int32)

In [255]:
arr2.max()

np.int32(10)

In [256]:
arr2.min()

np.int32(2)